---
- name: Deploy to K8s Cluster
  hosts: localhost
  become: ubuntu
  tasks:  # Added hyphen before "tasks"
    - name: Execute whoami command
      command: whoami > test.txt
      
 #   - name: Deploy Pod
 #     shell: |
  #      kubectl apply -f deployment.yaml

#    - name: Deploy Service
 #     shell: |
   #     kubectl apply -f pod.yaml
   
