---
- name: Deploy to K8s Cluster
  hosts: host
  become: ubuntu
  tasks:  # Added hyphen before "tasks"
    - name: Deploy Pod
      shell: |
        kubectl apply -f deployment.yaml

    - name: Deploy Service
      shell: |
        kubectl apply -f pod.yaml
