---
- name: Deploy to K8s Cluster 
  hosts: all
  become: ubuntu
tasks:
  - name: Deploy Pod
    shell: |
      kubectl apply -f deployment.yml
  
  - name: Deploy Service
    shell: | 
      kubectl apply -f pod.yml
