---
- name: Deploy to K8s Cluster
  hosts: localhost
  become: ubuntu
  tasks:  # Added hyphen before "tasks"
    - name: aws-cli & kctl install 
      command: chmod +x kubectl-aws.sh
        
    - name: aws-cli & kctl install 
      command: sh kubcetl-aws.sh

    - name: Deploy Pod
      shell: |
        kubectl apply -f deployment.yaml

    - name: Deploy Service
      shell: |
        kubectl apply -f pod.yaml
   
