apiVersion: apps/v1
kind: Deployment
metadata:     
  name: nginx-deployment  
  namespace: test  # Corrected indentation
  labels:
    app: nginx  
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: nginx
        image: shashwot/nginx-more
        ports:
        - containerPort: 80
