apiVersion: v1        
kind: Pod             
metadata:             
  name: nginx
  namespace: test     # Corrected indentation and removed capitalization
  labels:
    app: nginx
    tier: frontend
spec:                  
  containers:
  - name: nginx
    image: shashwot/nginx-more
